name: PlayTime
version: ${project.version}
main: me.pljr.playtime.PlayTime
api-version: 1.13
authors: [9hx]
depends: [PLJRApi]
description: Simpe plugin for calculating playtime of players.
commands:
  playtime:
    description: Main command for PlayTime.